author               = Lokrates
depends              = default
description          = A Minetest Mod to produce biofuel from unused plants.
min_minetest_version = 5.4
name                 = biofuel
optional_depends     = pipeworks, farming, pooper, wine, basic_materials, cucina_vegana, moretrees, vines, hopper, appliances, technic, ia_util
title                = IA Biofuel
version              = 0.9
